version: '3.5'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.11-management-alpine
    environment:
      - VHOST=rmqcpp # show test output on failure
    ports:
      - 15672:15672

  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile # name of your Dockerfile
    cap_add:
      - SYS_PTRACE # enable 'ptrace' inside the image for gdb
    security_opt:
      - seccomp:unconfined # disable some sys calls for root to enable gdb run
    volumes:
      - ..:/workarea
      - buildvolume:/workarea/build # store artifacts in a docker volume
    environment:
      - CTEST_OUTPUT_ON_FAILURE=1 # show test output on failure
    platform: linux/amd64
    depends_on:
      - rabbit

volumes:
  buildvolume: