// Copyright 2020-2023 Bloomberg Finance L.P.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// rmqa_rabbitcontextoptions.h
#ifndef INCLUDED_RMQA_RABBITCONTEXTOPTIONS
#define INCLUDED_RMQA_RABBITCONTEXTOPTIONS

#include <rmqp_metricpublisher.h>

#include <rmqp_consumertracing.h>
#include <rmqp_producertracing.h>
#include <rmqt_fieldvalue.h>
#include <rmqt_hosthealthconfig.h>
#include <rmqt_properties.h>
#include <rmqt_result.h>

#include <bdlmt_threadpool.h>
#include <bsl_memory.h>
#include <bsl_optional.h>
#include <bsl_set.h>
#include <bsl_variant.h>
#include <bsls_timeinterval.h>

namespace BloombergLP {
namespace rmqa {

/// \brief Class for passing arguments to RabbitContext
///
/// This class provides passing arguments to RabbitContext. It allows specifying
/// the async callback threadpool, metric publisher and error callback. If any
/// of them are not specified, a default value is used.

class RabbitContextOptions {
  public:
    typedef bsl::set<bsl::string> Tunables;

    /// \brief Tag type expressing no host health preference: it neither opts in
    /// nor opts out, leaving the choice to enclosing configuration layers. This
    /// is the alternative held by a default-constructed \c HostHealthSelection
    /// (the default). See \c setHostHealthSelection.
    struct HostHealthAwarenessUnset {};

    /// \brief Tag type selecting an explicit opt-out from host health
    /// awareness; see \c setHostHealthSelection. Selecting it is distinct from
    /// leaving the host health selection unset (\c HostHealthAwarenessUnset),
    /// which expresses no preference and lets enclosing configuration layers
    /// apply their own policy.
    struct HostHealthAwarenessOff {};

    /// \brief A caller's host health selection: exactly one of three mutually
    /// exclusive alternatives -- \c HostHealthAwarenessUnset (no preference;
    /// the default), \c rmqt::HostHealthConfig (opt-in; monitoring runs), or
    /// \c HostHealthAwarenessOff (explicit opt-out). A default-constructed
    /// selection holds \c HostHealthAwarenessUnset. See
    /// \c setHostHealthSelection.
    typedef bsl::variant<HostHealthAwarenessUnset,
                         rmqt::HostHealthConfig,
                         HostHealthAwarenessOff>
        HostHealthSelection;

    /// \brief By Default RabbitContext will
    /// 1) Create it's own threadpool for
    /// calling back to client code e.g. consuming messages, confirming
    /// published messages
    /// 2) Stub out error notifications - this library retries indefinitely for
    /// operations requested of it, set an error handler to be made aware of
    /// ongoing retry attempts in order to circuit break the retries for your
    /// applications needs
    /// 3) Stub out metric publishing, if you would like to publish metrics
    /// please provide an implementation that confirms to the MetricPublisher
    /// interface
    RabbitContextOptions();

    /// \param threadpool For async callbacks (e.g. as messages arrived for
    /// Consumer, and as confirmations arrive for Producer). By
    /// default a threadpool is created with the following parameters:
    ///     rmqp::Connection::s_threadPoolMinThreads
    ///     rmqp::Connection::s_threadPoolMaxThreads
    ///     rmqp::Connection::s_threadPoolMaxIdleTimeMs
    /// A custom threadpool can be provided if it is desirable for async
    /// callbacks to be executed in a shared threadpool, or to tune this
    /// threadpool. The provided threadpool must live longer than the
    /// RabbitContext
    RabbitContextOptions& setThreadpool(bdlmt::ThreadPool* threadpool);

    /// \param metricPublisher custom metric publisher will be used
    /// to publish different types of metrics generated by the library.
    RabbitContextOptions& setMetricPublisher(
        const bsl::shared_ptr<rmqp::MetricPublisher>& metricPublisher);

    /// \param errorCallback function will be called with error detail,
    /// when channel or connection is closed by rabbitmq broker.
    RabbitContextOptions&
    setErrorCallback(const rmqt::ErrorCallback& errorCallback);

    /// \param name name of client property to set
    /// \param value value of client property
    /// NOTE: The following properties are set by default and can be
    /// overridden: task, pid, os, os_version, os_patch, product, version.
    /// If product and version are provided, "product_chain" and
    /// "version_chain" fields are automatically populated showing the
    /// full library stack (e.g. product_chain="my-wrapper | rmqcpp C++ Client
    /// Library", version_chain="1.0.0 | 2.33.0").
    /// The following properties are reserved: capabilities, platform,
    /// connection_name. The product_chain and version_chain fields are
    /// automatically managed by the library stack and should not be set
    /// directly by applications.
    RabbitContextOptions& setClientProperty(const bsl::string& name,
                                            const rmqt::FieldValue& value);

    /// \brief Set time in which consumers should process messages
    /// \param timeout Message processing timeout
    /// This timeout specifies the time interval in which a consumer is
    /// supposed to process a message. If a consumer takes longer that the
    /// specified timeout, warnings will be logged.
    /// \note the library detects such cases periodically and the warnings
    /// generally won't be logged immediately after the given timeout expires.
    /// False-positive warnings may still be logged if the library has not
    /// processed the consumer acknowledgement before the timeout expires.
    RabbitContextOptions&
    setMessageProcessingTimeout(const bsls::TimeInterval& timeout);

    /// \brief Set time threshold at which point the error callback is called
    /// if there has been no success in establishing an amqp connection to the
    /// broker
    /// \param timeout the timeout value
    RabbitContextOptions& setConnectionErrorThreshold(
        const bsl::optional<bsls::TimeInterval>& timeout);

    /// \brief Set the maximum time a single connection-establishment attempt
    /// (TCP connect + TLS handshake + AMQP handshake) may take before it is
    /// aborted and retried. The library already bounds establishment with a
    /// default; this makes that bound configurable.
    /// \param timeout the establishment timeout, as a `bsls::TimeInterval` so
    /// that any resolution (down to nanoseconds) can be expressed -- e.g.
    /// `bsls::TimeInterval(5.0)` for five seconds, or
    /// `bsls::TimeInterval(0, 500 * 1000 * 1000)` for 500 milliseconds. If not
    /// set (`bsl::nullopt`), the library default is used. This only ever
    /// applies to the establishment phase -- it is cancelled once a connection
    /// is established -- so it does not affect long-lived connections. Lowering
    /// it makes the client give up on a stalled attempt and retry sooner;
    /// raising it tolerates slower networks/handshakes.
    /// \note The timeout is applied at millisecond granularity: the behavior
    /// is undefined unless `timeout`, when set, is at least one millisecond. A
    /// smaller (sub-millisecond) interval rounds down to zero, which would
    /// expire the bound immediately and prevent any connection from
    /// establishing.
    RabbitContextOptions& setConnectionEstablishmentTimeout(
        const bsl::optional<bsls::TimeInterval>& timeout);

    /// \brief will be called back to create a context which spans for the
    /// lifetime of the messageguard _before_ it is passed to its consumer
    /// message processor if there has
    /// \param consumerTracing implements the
    /// rmqp::ConsumerTracing protocol
    RabbitContextOptions& setConsumerTracing(
        const bsl::shared_ptr<rmqp::ConsumerTracing>& consumerTracing);

    /// \brief will be called back at message send, with meta data to establish
    /// a context, the context will be kept alive until the messageConfirm
    /// response callback
    /// \param producerTracing implements the
    /// rmqp::ProducerTracing protocol
    RabbitContextOptions& setProducerTracing(
        const bsl::shared_ptr<rmqp::ProducerTracing>& producerTracing);

    /// \brief DEPRECATED: Previously was used to switch between AMQP-spec
    /// and RabbitMQ-spec Field Value encoding. This is now always true
    RabbitContextOptions& useRabbitMQFieldValueEncoding(bool rabbitEncoding);

    /// \brief Shuffle endpoints rmq connects to.
    /// By default, boost asio (libc) resolves and connects
    /// to the node with longest matching subnet prefix
    /// causing disproportionately more connections with certain endpoints.
    /// Setting this option will shuffle resolver results.
    /// \param shuffleConnectionEndpoints set to true to shuffle.
    RabbitContextOptions&
    setShuffleConnectionEndpoints(bool shuffleConnectionEndpoints);

    /// \brief Set host health config for connections created by this context to
    /// ensure that RabbitMQ consumers are connected from healthy hosts.
    /// When host health config is set, the host health monitor is created and
    /// consumers with \c consumeOnlyFromHealthyHost enabled (the default) will
    /// pause message delivery when the host becomes unhealthy and resume when
    /// the host is deemed healthy again.
    /// \note By default, \c ConsumerConfig::consumeOnlyFromHealthyHost is true,
    /// meaning consumers automatically participate in host health monitoring
    /// when host health config is set at the context level. Consumers can
    /// opt out by calling \c
    /// ConsumerConfig::setConsumeOnlyFromHealthyHost(false). If host health
    /// config is not set, \c consumeOnlyFromHealthyHost has no effect.
    ///
    /// \param hostHealthConfig configuration for host health monitoring
    ///
    /// \note This is a convenience equivalent to \c setHostHealthSelection with
    /// a \c HostHealthConfig: selecting a config is what causes the monitor to
    /// run, and it replaces any prior opt-out selection. Leaving the selection
    /// unset (the default) expresses no preference.
    RabbitContextOptions&
    setHostHealthConfig(const rmqt::HostHealthConfig& hostHealthConfig);

    /// \brief Set the caller's host health selection: a \c HostHealthConfig to
    /// opt in (monitoring runs) or \c HostHealthAwarenessOff to explicitly
    /// opt out (no monitor is created even if a config could otherwise be
    /// attached). The alternatives are mutually exclusive -- this replaces any
    /// previously set config or opt-out. Not calling this at all leaves the
    /// selection unset (the default), which expresses no preference and lets
    /// enclosing configuration layers apply their own policy.
    /// \param selection the host health selection
    RabbitContextOptions&
    setHostHealthSelection(const HostHealthSelection& selection);

    bdlmt::ThreadPool* threadpool() const { return d_threadpool; }

    const bsl::shared_ptr<rmqp::MetricPublisher>& metricPublisher() const
    {
        return d_metricPublisher;
    }

    const rmqt::ErrorCallback& errorCallback() const { return d_onError; }

    const rmqt::FieldTable& clientProperties() const
    {
        return d_clientProperties;
    }

    const bsls::TimeInterval& messageProcessingTimeout() const
    {
        return d_messageProcessingTimeout;
    }

    const bsl::optional<bsls::TimeInterval>& connectionErrorThreshold() const
    {
        return d_connectionErrorThreshold;
    }

    const bsl::optional<bsls::TimeInterval>&
    connectionEstablishmentTimeout() const
    {
        return d_connectionEstablishmentTimeout;
    }

    const rmqt::Tunables& tunables() const { return d_tunables; }

    const bsl::shared_ptr<rmqp::ConsumerTracing>& consumerTracing() const
    {
        return d_consumerTracing;
    }

    const bsl::shared_ptr<rmqp::ProducerTracing>& producerTracing() const
    {
        return d_producerTracing;
    }

    const bsl::optional<bool>& shuffleConnectionEndpoints() const
    {
        return d_shuffleConnectionEndpoints;
    }

    /// \brief Get the caller's host health selection. The returned variant
    /// holds \c HostHealthAwarenessUnset when no preference has been expressed
    /// (the default), a \c rmqt::HostHealthConfig when opted in (via
    /// \c setHostHealthSelection or \c setHostHealthConfig), or a
    /// \c HostHealthAwarenessOff when explicitly opted out.
    /// \return The host health selection
    const HostHealthSelection& hostHealthSelection() const
    {
        return d_hostHealthSelection;
    }

#ifdef USES_LIBRMQ_EXPERIMENTAL_FEATURES
    RabbitContextOptions& setTunable(const bsl::string& tunable);
#endif

  private:
    // Members are ordered to minimize padding (see
    // clang-analyzer-optin.performance.Padding), not by logical grouping. The
    // constructor's initializer list mirrors this order to avoid -Wreorder.
    static const int DEFAULT_MESSAGE_PROCESSING_TIMEOUT = 60;
    rmqt::ErrorCallback d_onError;
    HostHealthSelection d_hostHealthSelection;
    bdlmt::ThreadPool* d_threadpool;
    bsl::shared_ptr<rmqp::MetricPublisher> d_metricPublisher;
    bsls::TimeInterval d_messageProcessingTimeout;
    bsl::shared_ptr<rmqp::ConsumerTracing> d_consumerTracing;
    bsl::shared_ptr<rmqp::ProducerTracing> d_producerTracing;
    bsl::optional<bsls::TimeInterval> d_connectionErrorThreshold;
    bsl::optional<bsls::TimeInterval> d_connectionEstablishmentTimeout;
    rmqt::FieldTable d_clientProperties;
    rmqt::Tunables d_tunables;
    bsl::optional<bool> d_shuffleConnectionEndpoints;
};

} // namespace rmqa
} // namespace BloombergLP

#endif
